/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicauca.parqueadero.presentacion;

import com.unicauca.parqueadero.negocio.Conductor;
import com.unicauca.parqueadero.negocio.GestorConductor;
import com.unicauca.parqueadero.negocio.Vehiculo;
import com.unicauca.parqueadero.utilidades.Utilidades;
import java.awt.Color;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author JuanCamilo
 */
public class GUIBusquedaConductor extends javax.swing.JInternalFrame implements Observer{

    /**
     * Creates new form GUIBusquedaConductor
     */
    private GUIParqueaderoController pController;
    private GestorConductor modelo;
    private GUIRegistroConductor registroCon;
    private GUIRegistroVehiculo regisVehi;
    private String c_cedula;
    private String v_placa;

    public GUIBusquedaConductor() {
        initComponents();
        inicializarTabla();
        this.setSize(1000, 400);
        this.setResizable(true);
        this.setClosable(true);
        this.txtDocumento.requestFocus();
    }
    public void setRegVehiculo(GUIRegistroVehiculo vista){
        this.regisVehi = vista;
    }
    public void setPController(GUIParqueaderoController controller) {
        this.pController = controller;
    }

    public void setModelo(GestorConductor modelo) {
        this.modelo = modelo;
    }

    public void setRegistroCon(GUIRegistroConductor registro) {
        this.registroCon = registro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotones = new javax.swing.JPanel();
        btnAsignarPuesto = new javax.swing.JButton();
        pnlResultados = new javax.swing.JPanel();
        lblInfoConductor = new javax.swing.JLabel();
        pblTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        pnlAddVehiculo = new javax.swing.JPanel();
        btnAddVehiculo = new javax.swing.JButton();
        pnlBusqueda = new javax.swing.JPanel();
        lblTituloIngrese = new javax.swing.JLabel();
        pblCampo = new javax.swing.JPanel();
        txtDocumento = new javax.swing.JTextField();
        pnlTipoDocumento = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/buscar.png"))); // NOI18N

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        btnAsignarPuesto.setBackground(new java.awt.Color(0, 51, 51));
        btnAsignarPuesto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnAsignarPuesto.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarPuesto.setText("Asignar Puesto");
        btnAsignarPuesto.setEnabled(false);
        btnAsignarPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarPuestoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsignarPuesto, java.awt.BorderLayout.PAGE_END);

        pnlResultados.setLayout(new java.awt.BorderLayout());

        lblInfoConductor.setBackground(new java.awt.Color(255, 255, 255));
        lblInfoConductor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblInfoConductor.setText("INFORMACION");
        pnlResultados.add(lblInfoConductor, java.awt.BorderLayout.NORTH);

        pblTabla.setBackground(new java.awt.Color(0, 102, 102));
        pblTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VEHICULOS ASOCIADOS AL NUMERO DE DOCUMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        pblTabla.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 102, 102));

        tblResultado.setBackground(new java.awt.Color(0, 102, 102));
        tblResultado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tblResultado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblResultado.setForeground(new java.awt.Color(255, 255, 255));
        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResultado.setGridColor(new java.awt.Color(51, 255, 255));
        tblResultado.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultado);

        pblTabla.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlAddVehiculo.setBackground(new java.awt.Color(0, 102, 102));
        pnlAddVehiculo.setLayout(new java.awt.BorderLayout());

        btnAddVehiculo.setBackground(new java.awt.Color(0, 51, 51));
        btnAddVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnAddVehiculo.setText("Agregar Vehículo");
        btnAddVehiculo.setEnabled(false);
        btnAddVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehiculoActionPerformed(evt);
            }
        });
        pnlAddVehiculo.add(btnAddVehiculo, java.awt.BorderLayout.NORTH);

        pblTabla.add(pnlAddVehiculo, java.awt.BorderLayout.LINE_END);

        pnlResultados.add(pblTabla, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlResultados, java.awt.BorderLayout.CENTER);

        pnlBusqueda.setBackground(new java.awt.Color(0, 102, 102));

        lblTituloIngrese.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloIngrese.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloIngrese.setText("Ingrese el numero de documento");
        pnlBusqueda.add(lblTituloIngrese);

        pblCampo.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout pblCampoLayout = new javax.swing.GroupLayout(pblCampo);
        pblCampo.setLayout(pblCampoLayout);
        pblCampoLayout.setHorizontalGroup(
            pblCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
            .addGroup(pblCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pblCampoLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );
        pblCampoLayout.setVerticalGroup(
            pblCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pblCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pblCampoLayout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        pnlBusqueda.add(pblCampo);

        pnlTipoDocumento.setBackground(new java.awt.Color(0, 153, 153));
        pnlTipoDocumento.setLayout(new java.awt.GridLayout(2, 1));
        pnlBusqueda.add(pnlTipoDocumento);

        btnConsultar.setBackground(new java.awt.Color(0, 204, 204));
        btnConsultar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/buscar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        pnlBusqueda.add(btnConsultar);

        getContentPane().add(pnlBusqueda, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (txtDocumento.getText().length() > 0) {
            
            String cedula = txtDocumento.getText();
            Conductor aux = modelo.consultarConductor(cedula);//Guarda el conductor con el numero de cedula ingresado
            if (aux == null) {
                Utilidades.mensajeAdvertencia("No se encuentró conductor con el numero ingresado,debera agregarse manualmente", "No se encontro el conductor");
                registroCon.setCedula(cedula);
                registroCon.iniciar();
            } else {
                lblInfoConductor.setText("INFORMACION: Nombre: " + aux.getNombres() + " Apellidos: " + aux.getApellidos() + " Rol: " + aux.getRol());

                if (!modelo.obtenerVehiculosCon(cedula).isEmpty()) {
                    llenarTabla(modelo.obtenerVehiculosCon(cedula));
                    this.btnAddVehiculo.setEnabled(true);
                    c_cedula = aux.getCedula();

                } else {
                    Utilidades.mensajeAdvertencia("No se encuentran vehiculos asociados,el registro del vehiculo se debe hacer manualmentes", "No se encuentran vehiculos asociados");
                    regisVehi.setCedula(cedula);
                    regisVehi.iniciar();
                }
            }
        }else{
            Utilidades.mensajeAdvertencia("Por favor ingrese un documento", "Campo Vacio");
            this.txtDocumento.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAsignarPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarPuestoActionPerformed
        pController.setCedula(c_cedula);
        pController.setPlaca(v_placa);
        pController.iniciar();
        pController.lanzarHilo();
        pController.detenrHilo();
        this.txtDocumento.setText("");
        inicializarTabla();
        lblInfoConductor.setText("INFORMACION: ");
        this.btnAsignarPuesto.setEnabled(false);
        this.txtDocumento.requestFocus();
        this.btnAddVehiculo.setEnabled(false);

    }//GEN-LAST:event_btnAsignarPuestoActionPerformed

    private void tblResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultadoMouseClicked
        int seleccionar = tblResultado.rowAtPoint(evt.getPoint());
        String placa = String.valueOf(tblResultado.getValueAt(seleccionar, 0));
        v_placa = placa;
        this.btnAsignarPuesto.setEnabled(true);
    }//GEN-LAST:event_tblResultadoMouseClicked

    private void btnAddVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehiculoActionPerformed
        if(!txtDocumento.getText().isEmpty()){
            String cedula;
            cedula = txtDocumento.getText();
            regisVehi.setCedula(cedula);
            regisVehi.iniciar();
        }else{
            Utilidades.mensajeError("Faltan Campos por completar", "Campos Facios");
        }
    }//GEN-LAST:event_btnAddVehiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVehiculo;
    private javax.swing.JButton btnAsignarPuesto;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfoConductor;
    private javax.swing.JLabel lblTituloIngrese;
    private javax.swing.JPanel pblCampo;
    private javax.swing.JPanel pblTabla;
    private javax.swing.JPanel pnlAddVehiculo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlResultados;
    private javax.swing.JPanel pnlTipoDocumento;
    private javax.swing.JTable tblResultado;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables

    private void inicializarTabla() {
        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Placa", "Marca", "Tipo"
                }
        ));
    }

    private void llenarTabla(ArrayList<Vehiculo> vehiculos) {
        this.inicializarTabla();
        DefaultTableModel model = (DefaultTableModel) tblResultado.getModel();

        Object rowData[] = new Object[3];
        for (Vehiculo ve : vehiculos) {
            rowData[0] = ve.getPlaca();
            rowData[1] = ve.getMarca();
            rowData[2] = ve.getTipo();
            model.addRow(rowData);
        }
    }

    public JButton getBtnConsultar() {
        return this.btnConsultar;
    }

    @Override
    public void update(Observable o, Object arg) {
         btnConsultar.doClick();
    }
}
