/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicauca.parqueadero.presentacion;

import com.unicauca.parqueadero.negocio.GestorConductor;
import com.unicauca.parqueadero.utilidades.Utilidades;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author JuanCamilo
 */
public class GUIMultas extends javax.swing.JFrame {

    /**
     * Creates new form GUIMultas
     */
    private GestorConductor gestor;
    private String ruta="";
    public GUIMultas() {
        gestor = new GestorConductor();
        initComponents();
        this.setTitle("AGREGAR UNA MULTA");
        Image icon = Toolkit.getDefaultToolkit().getImage("./src/recursos/papel.png");
        this.setIconImage(icon);
    }
    public void iniciar(){
        this.setSize(616,213);
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescripcion = new javax.swing.JTextArea();
        lblExplorador = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAddFoto = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registro de Multas");
        getContentPane().add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        pnlDatos.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        lblPlaca.setText("Ingrese la Placa");
        pnlDatos.add(lblPlaca);
        pnlDatos.add(txtPlaca);

        lblDescripcion.setText("Descripcion:");
        pnlDatos.add(lblDescripcion);

        txtaDescripcion.setColumns(20);
        txtaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtaDescripcion);

        pnlDatos.add(jScrollPane1);
        pnlDatos.add(lblExplorador);

        btnAddFoto.setText("Agregar Foto");
        btnAddFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(btnAddFoto)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddFoto)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlDatos.add(jPanel1);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFotoActionPerformed
        ruta="";
        ImageIcon icono;
        JFileChooser j = new JFileChooser();
        int ret = j.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){
            ruta = j.getSelectedFile().getAbsolutePath();
            ImageIcon imagen = new ImageIcon(ruta);
            icono = new ImageIcon(imagen.getImage().getScaledInstance(lblExplorador.getWidth(), lblExplorador.getHeight(), Image.SCALE_DEFAULT));
            lblExplorador.setIcon(icono);
            this.repaint();
            
        }
        System.out.println(ruta);
    }//GEN-LAST:event_btnAddFotoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(!txtPlaca.getText().isEmpty() && !txtaDescripcion.getText().isEmpty() && !ruta.equals("")){
            String placa,descripcion;
            placa = txtPlaca.getText();
            descripcion = txtaDescripcion.getText();
            if(gestor.agregarMulta(placa, descripcion, ruta)){
                Utilidades.mensajeExito("Registro Exitoso", "Exito");
                limpiarCajas();
                this.dispose();
            }else{
                Utilidades.mensajeError("Un error inesperado ha ocurrido", "ERROR");
            }
                           
        }else{
            Utilidades.mensajeAdvertencia("Faltan campos por completar", "ADVERTENCIA");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    private void limpiarCajas(){
        this.txtPlaca.setText("");
        this.txtaDescripcion.setText("");
        this.lblExplorador.setIcon(null);
        this.lblExplorador.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFoto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblExplorador;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextArea txtaDescripcion;
    // End of variables declaration//GEN-END:variables
}
