/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicauca.parqueadero.presentacion;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.WindowConstants;
import com.unicauca.parqueadero.negocio.IEstrategiaParqueadero;

/**
 *
 * @author JuanCamilo
 */
public class GUIParqueadero extends javax.swing.JFrame {

    private ArrayList<JToggleButton> tmp;
    private IEstrategiaParqueadero estrategia;
    private GUIParqueadero vista;

    /**
     * Creates new form GUIParqueaderoSur
     */
    public GUIParqueadero() {
        vista = this;
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.out.println("Cerro hilo");
                estrategia.terminarHilo();
                vista.dispose();
            }
        });
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("./src/recursos/mapa.png");
        this.setIconImage(icon);
        guardarBotones();
        //this.hilo.start();

    }

    public void cerrar() {
        this.dispose();
    }

    public void habilitar(int i, boolean es_entrada) {
        if (es_entrada) {
            tmp.get(i).setBackground(new Color(240, 240, 240));
            tmp.get(i).setSelected(false);
            tmp.get(i).setEnabled(true);
        } else {
            tmp.get(i).setBackground(Color.green);
            tmp.get(i).setSelected(false);
            tmp.get(i).setEnabled(true);
        }
    }

    public void deshabilitar(int i,boolean es_entrada) {
        if(es_entrada){
        tmp.get(i).setBackground(Color.green);
        tmp.get(i).setSelected(false);
        tmp.get(i).setEnabled(false);
        }else{
            tmp.get(i).setBackground(new Color(240, 240, 240));
            tmp.get(i).setSelected(false);
            tmp.get(i).setEnabled(false);
        }
    }

    public void cambiarColor(int indice) {
        tmp.get(indice).setBackground(Color.green);
        tmp.get(indice).setSelected(false);
        tmp.get(indice).setEnabled(false);
    }

    public void setEstrategia(IEstrategiaParqueadero est) {
        this.estrategia = est;
    }

    public void habilitarSalida(int i) {
        tmp.get(i).setEnabled(true);
    }

    public void cambiarColorSalida(int i) {
        tmp.get(i).setBackground(new Color(240, 240, 240));
        tmp.get(i).setSelected(false);
        tmp.get(i).setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlParqueadero = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnlZonaMotos = new javax.swing.JPanel();
        btn32 = new javax.swing.JToggleButton();
        btn33 = new javax.swing.JToggleButton();
        btn35 = new javax.swing.JToggleButton();
        btn36 = new javax.swing.JToggleButton();
        btn37 = new javax.swing.JToggleButton();
        btn38 = new javax.swing.JToggleButton();
        btn34 = new javax.swing.JToggleButton();
        btn39 = new javax.swing.JToggleButton();
        btn40 = new javax.swing.JToggleButton();
        btn31 = new javax.swing.JToggleButton();
        pnlIpet = new javax.swing.JPanel();
        btn25 = new javax.swing.JToggleButton();
        btn26 = new javax.swing.JToggleButton();
        btn27 = new javax.swing.JToggleButton();
        btn28 = new javax.swing.JToggleButton();
        btn30 = new javax.swing.JToggleButton();
        btn29 = new javax.swing.JToggleButton();
        pnlFic = new javax.swing.JPanel();
        btn16 = new javax.swing.JToggleButton();
        btn18 = new javax.swing.JToggleButton();
        btn20 = new javax.swing.JToggleButton();
        btn21 = new javax.swing.JToggleButton();
        btn22 = new javax.swing.JToggleButton();
        btn23 = new javax.swing.JToggleButton();
        btn24 = new javax.swing.JToggleButton();
        btn17 = new javax.swing.JToggleButton();
        btn19 = new javax.swing.JToggleButton();
        pnlFiet = new javax.swing.JPanel();
        btn2 = new javax.swing.JToggleButton();
        btn5 = new javax.swing.JToggleButton();
        btn6 = new javax.swing.JToggleButton();
        btn7 = new javax.swing.JToggleButton();
        btn8 = new javax.swing.JToggleButton();
        btn9 = new javax.swing.JToggleButton();
        btn10 = new javax.swing.JToggleButton();
        btn11 = new javax.swing.JToggleButton();
        btn12 = new javax.swing.JToggleButton();
        btn13 = new javax.swing.JToggleButton();
        btn14 = new javax.swing.JToggleButton();
        btn15 = new javax.swing.JToggleButton();
        btn3 = new javax.swing.JToggleButton();
        btn4 = new javax.swing.JToggleButton();
        btn1 = new javax.swing.JToggleButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlOcupado = new javax.swing.JPanel();
        btnOcupado = new javax.swing.JButton();
        lblOcupado = new javax.swing.JLabel();
        lblEspacioVacio = new javax.swing.JLabel();
        pnlLibre = new javax.swing.JPanel();
        btlnLibre = new javax.swing.JButton();
        lblLibre = new javax.swing.JLabel();

        pnlParqueadero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Laboratorios"));
        pnlParqueadero.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 80, 220));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("IPET"));
        pnlParqueadero.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 110, 40));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("FIET"));
        pnlParqueadero.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, 260));

        pnlZonaMotos.setBackground(new java.awt.Color(153, 153, 153));
        pnlZonaMotos.setBorder(javax.swing.BorderFactory.createTitledBorder("Zona Motos"));
        pnlZonaMotos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn32.setText("32");
        btn32.setBorder(null);
        pnlZonaMotos.add(btn32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 30, 30));

        btn33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn33.setText("33");
        btn33.setBorder(null);
        pnlZonaMotos.add(btn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 30, 30));

        btn35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn35.setText("35");
        btn35.setBorder(null);
        pnlZonaMotos.add(btn35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 30, 30));

        btn36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn36.setText("36");
        btn36.setBorder(null);
        pnlZonaMotos.add(btn36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 30, 30));

        btn37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn37.setText("37");
        btn37.setBorder(null);
        pnlZonaMotos.add(btn37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 30, 30));

        btn38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn38.setText("38");
        btn38.setBorder(null);
        pnlZonaMotos.add(btn38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 30, 30));

        btn34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn34.setText("34");
        btn34.setBorder(null);
        pnlZonaMotos.add(btn34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 30, 30));

        btn39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn39.setText("39");
        btn39.setBorder(null);
        pnlZonaMotos.add(btn39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 30, 30));

        btn40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn40.setText("40");
        btn40.setBorder(null);
        pnlZonaMotos.add(btn40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 30, 30));

        btn31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn31.setText("31");
        btn31.setBorder(null);
        pnlZonaMotos.add(btn31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        pnlParqueadero.add(pnlZonaMotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 90, 220));

        pnlIpet.setBackground(new java.awt.Color(153, 153, 153));
        pnlIpet.setBorder(javax.swing.BorderFactory.createTitledBorder("Zona IPET"));
        pnlIpet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn25.setText("25");
        btn25.setBorder(null);
        pnlIpet.add(btn25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        btn26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn26.setText("26");
        btn26.setBorder(null);
        pnlIpet.add(btn26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 30, 30));

        btn27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn27.setText("27");
        btn27.setBorder(null);
        pnlIpet.add(btn27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 30, 30));

        btn28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn28.setText("28");
        btn28.setBorder(null);
        pnlIpet.add(btn28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 30, 30));

        btn30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn30.setText("30");
        btn30.setBorder(null);
        pnlIpet.add(btn30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 30, 30));

        btn29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn29.setText("29");
        btn29.setBorder(null);
        pnlIpet.add(btn29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 30, 30));

        pnlParqueadero.add(pnlIpet, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 140, 100));

        pnlFic.setBackground(new java.awt.Color(153, 153, 153));
        pnlFic.setBorder(javax.swing.BorderFactory.createTitledBorder("Zona FIC"));
        pnlFic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn16.setText("16");
        btn16.setBorder(null);
        pnlFic.add(btn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        btn18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn18.setText("18");
        btn18.setBorder(null);
        pnlFic.add(btn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 30, 30));

        btn20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn20.setText("20");
        btn20.setBorder(null);
        pnlFic.add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 30, 30));

        btn21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn21.setText("21");
        btn21.setBorder(null);
        pnlFic.add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 30, 30));

        btn22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn22.setText("22");
        btn22.setBorder(null);
        pnlFic.add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 30, 30));

        btn23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn23.setText("23");
        btn23.setBorder(null);
        pnlFic.add(btn23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 30, 30));

        btn24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn24.setText("24");
        btn24.setBorder(null);
        pnlFic.add(btn24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 30, 30));

        btn17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn17.setText("17");
        btn17.setBorder(null);
        pnlFic.add(btn17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 30, 30));

        btn19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn19.setText("19");
        btn19.setBorder(null);
        pnlFic.add(btn19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 30, 30));

        pnlParqueadero.add(pnlFic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, 140));

        pnlFiet.setBackground(new java.awt.Color(153, 153, 153));
        pnlFiet.setBorder(javax.swing.BorderFactory.createTitledBorder("Zona Fiet"));
        pnlFiet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn2.setText("2");
        btn2.setBorder(null);
        pnlFiet.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 30, 30));

        btn5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn5.setText("5");
        btn5.setBorder(null);
        pnlFiet.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 30, 30));

        btn6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn6.setText("6");
        btn6.setBorder(null);
        pnlFiet.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 30, 30));

        btn7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn7.setText("7");
        btn7.setBorder(null);
        pnlFiet.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 30, 30));

        btn8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn8.setText("8");
        btn8.setBorder(null);
        pnlFiet.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 30, 30));

        btn9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn9.setText("9");
        btn9.setBorder(null);
        pnlFiet.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 30, 30));

        btn10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn10.setText("10");
        btn10.setBorder(null);
        pnlFiet.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 30, 30));

        btn11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn11.setText("11");
        btn11.setBorder(null);
        pnlFiet.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 30, 30));

        btn12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn12.setText("12");
        btn12.setBorder(null);
        pnlFiet.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 30, 30));

        btn13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn13.setText("13");
        btn13.setBorder(null);
        pnlFiet.add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 30, 30));

        btn14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn14.setText("14");
        btn14.setBorder(null);
        pnlFiet.add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 30, 30));

        btn15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn15.setText("15");
        btn15.setBorder(null);
        pnlFiet.add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 30, 30));

        btn3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn3.setText("3");
        btn3.setBorder(null);
        pnlFiet.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 30, 30));

        btn4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn4.setText("4");
        btn4.setBorder(null);
        pnlFiet.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 30, 30));

        btn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn1.setText("1");
        btn1.setBorder(null);
        pnlFiet.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        pnlParqueadero.add(pnlFiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, 240));

        getContentPane().add(pnlParqueadero, java.awt.BorderLayout.CENTER);

        pnlTitulo.setLayout(new java.awt.GridLayout(2, 2));

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTitulo.setText("PARQUEADERO UNICAUCA");
        pnlTitulo.add(lblTitulo);

        pnlOcupado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOcupado.setBackground(new java.awt.Color(0, 255, 0));
        pnlOcupado.add(btnOcupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 20, 20));

        lblOcupado.setText("OCUPADO");
        pnlOcupado.add(lblOcupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 283, 20));

        pnlTitulo.add(pnlOcupado);
        pnlTitulo.add(lblEspacioVacio);

        pnlLibre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btlnLibre.setBackground(new java.awt.Color(255, 255, 255));
        pnlLibre.add(btlnLibre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 20, 20));

        lblLibre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLibre.setText("LIBRE");
        pnlLibre.add(lblLibre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlTitulo.add(pnlLibre);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    public void pintarTodos() {
        for (int i = 0; i < tmp.size(); i++) {
            tmp.get(i).setSelected(false);
            tmp.get(i).setEnabled(true);
        }
    }

    public ArrayList<JToggleButton> getBotones() {
        return tmp;
    }

    private void guardarBotones() {
        this.tmp = new ArrayList<>();
        tmp.add(btn1);
        tmp.add(btn2);
        tmp.add(btn3);
        tmp.add(btn4);
        tmp.add(btn5);
        tmp.add(btn6);
        tmp.add(btn7);
        tmp.add(btn8);
        tmp.add(btn9);
        tmp.add(btn10);
        tmp.add(btn11);
        tmp.add(btn12);
        tmp.add(btn13);
        tmp.add(btn14);
        tmp.add(btn15);
        tmp.add(btn16);
        tmp.add(btn17);
        tmp.add(btn18);
        tmp.add(btn19);
        tmp.add(btn20);
        tmp.add(btn21);
        tmp.add(btn22);
        tmp.add(btn23);
        tmp.add(btn24);
        tmp.add(btn25);
        tmp.add(btn26);
        tmp.add(btn27);
        tmp.add(btn28);
        tmp.add(btn29);
        tmp.add(btn30);
        tmp.add(btn31);
        tmp.add(btn32);
        tmp.add(btn32);
        tmp.add(btn33);
        tmp.add(btn34);
        tmp.add(btn35);
        tmp.add(btn36);
        tmp.add(btn37);
        tmp.add(btn38);
        tmp.add(btn39);
        tmp.add(btn40);

    }

    public JPanel getFiet() {
        return pnlFiet;
    }

    public JPanel getFic() {
        return pnlFic;
    }

    public JPanel getIpet() {
        return pnlIpet;
    }

    public JPanel getMotos() {
        return pnlZonaMotos;
    }

    public ArrayList<JPanel> getZonas() {
        ArrayList<JPanel> aux = new ArrayList<>();
        aux.add(pnlFiet);
        aux.add(pnlFic);
        aux.add(pnlIpet);
        aux.add(pnlZonaMotos);
        return aux;
    }

    public void deshabilitarVista() {
        for (int i = 0; i < this.getZonas().size(); i++) {
            for (Component component : this.getZonas().get(i).getComponents()) {
                component.setEnabled(false);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlnLibre;
    private javax.swing.JToggleButton btn1;
    private javax.swing.JToggleButton btn10;
    private javax.swing.JToggleButton btn11;
    private javax.swing.JToggleButton btn12;
    private javax.swing.JToggleButton btn13;
    private javax.swing.JToggleButton btn14;
    private javax.swing.JToggleButton btn15;
    private javax.swing.JToggleButton btn16;
    private javax.swing.JToggleButton btn17;
    private javax.swing.JToggleButton btn18;
    private javax.swing.JToggleButton btn19;
    private javax.swing.JToggleButton btn2;
    private javax.swing.JToggleButton btn20;
    private javax.swing.JToggleButton btn21;
    private javax.swing.JToggleButton btn22;
    private javax.swing.JToggleButton btn23;
    private javax.swing.JToggleButton btn24;
    private javax.swing.JToggleButton btn25;
    private javax.swing.JToggleButton btn26;
    private javax.swing.JToggleButton btn27;
    private javax.swing.JToggleButton btn28;
    private javax.swing.JToggleButton btn29;
    private javax.swing.JToggleButton btn3;
    private javax.swing.JToggleButton btn30;
    private javax.swing.JToggleButton btn31;
    private javax.swing.JToggleButton btn32;
    private javax.swing.JToggleButton btn33;
    private javax.swing.JToggleButton btn34;
    private javax.swing.JToggleButton btn35;
    private javax.swing.JToggleButton btn36;
    private javax.swing.JToggleButton btn37;
    private javax.swing.JToggleButton btn38;
    private javax.swing.JToggleButton btn39;
    private javax.swing.JToggleButton btn4;
    private javax.swing.JToggleButton btn40;
    private javax.swing.JToggleButton btn5;
    private javax.swing.JToggleButton btn6;
    private javax.swing.JToggleButton btn7;
    private javax.swing.JToggleButton btn8;
    private javax.swing.JToggleButton btn9;
    private javax.swing.JButton btnOcupado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEspacioVacio;
    private javax.swing.JLabel lblLibre;
    private javax.swing.JLabel lblOcupado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFic;
    private javax.swing.JPanel pnlFiet;
    private javax.swing.JPanel pnlIpet;
    private javax.swing.JPanel pnlLibre;
    private javax.swing.JPanel pnlOcupado;
    private javax.swing.JPanel pnlParqueadero;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlZonaMotos;
    // End of variables declaration//GEN-END:variables
      Thread hilo = new Thread() {
        @Override
        public void run() {
            int segundos = 0;
            try {
                while (true) {
                    Thread.sleep(1000);
                    segundos++;
                    if (segundos >= 3) {
                        System.out.println("Cargar mapa");
                        //estrategia.cargarPuesto(vista);
                        segundos = 0;
                    }
                }
            } catch (Exception e) {
                System.out.println("Ocurrio una exepcion");
            }
            System.out.println("Afuera del hilo");

        }
    };

}
