/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicauca.parqueadero.presentacion;

import com.unicauca.parqueadero.negocio.GestorConductor;
import com.unicauca.parqueadero.utilidades.Utilidades;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author JuanCamilo
 */
public class GUIRegistroVehiculo extends javax.swing.JFrame {
    private boolean registro = false;
    private GestorConductor modelo;
    private String v_placa; 
    private String cedula;
    /**
     * Creates new form GUIRegistroAuto
     */
    public GUIRegistroVehiculo() {
        initComponents();


    }
    public void setModelo(GestorConductor gestor){
        this.modelo = gestor;
    }
    public void setCedula(String ced){
        this.cedula = ced;
    }
    public void iniciar() {
        this.setSize(500, 210);
        this.setTitle("REGISTRO DE VEHICULO");
        Image icon = Toolkit.getDefaultToolkit().getImage("./src/recursos/coche-deportivo.png");
        this.setIconImage(icon);
        this.cbxTipo.removeAllItems();
        this.cbxTipo.addItem("Moto");
        this.cbxTipo.addItem("Automovil");
        this.setLocation(400, 250);
        this.setVisible(true);
    }
    public boolean getRegistro(){
        return registro;
    } 
    public String getPlaca(){
        return v_placa;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        pnlBotones = new javax.swing.JPanel();
        brtRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDatos.setBackground(new java.awt.Color(0, 102, 102));
        pnlDatos.setLayout(new java.awt.GridLayout(3, 2, 1, 4));

        lblPlaca.setBackground(new java.awt.Color(0, 102, 102));
        lblPlaca.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lblPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaca.setText("Ingrese la placa :");
        pnlDatos.add(lblPlaca);
        pnlDatos.add(txtPlaca);

        lblMarca.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarca.setText("Ingrese la marca:");
        pnlDatos.add(lblMarca);
        pnlDatos.add(txtMarca);

        lblTipo.setBackground(new java.awt.Color(255, 255, 255));
        lblTipo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("Ingrese el tipo:");
        pnlDatos.add(lblTipo);

        cbxTipo.setBackground(new java.awt.Color(0, 153, 153));
        cbxTipo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        cbxTipo.setForeground(new java.awt.Color(255, 255, 255));
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        pnlDatos.add(cbxTipo);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.CENTER);

        pnlBotones.setBackground(new java.awt.Color(0, 102, 102));

        brtRegistrar.setBackground(new java.awt.Color(0, 255, 255));
        brtRegistrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        brtRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/guardar.png"))); // NOI18N
        brtRegistrar.setText("Registrar");
        brtRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brtRegistrarActionPerformed(evt);
            }
        });
        pnlBotones.add(brtRegistrar);

        btnCancelar.setBackground(new java.awt.Color(0, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pnlTitulo.setBackground(new java.awt.Color(0, 102, 102));

        lblTitulo.setBackground(new java.awt.Color(0, 102, 102));
        lblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("REGISTRO DE VEHICULO");
        pnlTitulo.add(lblTitulo);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void brtRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brtRegistrarActionPerformed

        if (!txtMarca.getText().isEmpty() && !txtPlaca.getText().isEmpty()) {
            GestorConductor gestor = new GestorConductor();
            String placa, marca, tipo;
            placa = txtPlaca.getText();
            marca = txtMarca.getText();
            tipo = cbxTipo.getSelectedItem().toString();
            try{
                gestor.agregarVehiculo(placa, marca, tipo);
                modelo.asociarVehiCond(cedula, placa);
                Utilidades.mensajeExito("Vehiculo registrado con exito", "Exito");
                registro = true;
                v_placa = placa;
                this.dispose();
            }
            catch(Exception e){
                Utilidades.mensajeError("Un error inesperado ha ocurrido","Error");
            }
        }else{
            Utilidades.mensajeError("Todos los capos son obligatorios", "Campos Vacios");
        }
    }//GEN-LAST:event_brtRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brtRegistrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
