/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicauca.parqueadero.presentacion;

import com.unicauca.parqueadero.utilidades.Utilidades;
import java.util.Properties;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import recursos.DateLabelFormatter;

/**
 *
 * @author JuanCamilo
 */
public class GUIRegistroVigilante extends javax.swing.JPanel {
    
    private JDatePickerImpl dtpFechaNaci;
    private  JDatePickerImpl datePicker;
    /**
     * Creates new form GUIRegistroVigilante
     */
    public GUIRegistroVigilante() {
        initComponents();
    }
    public void iniciar(){
        UtilDateModel model = new UtilDateModel();
        Properties p = new Properties();
        p.put("text.year", "Year");
        p.put("text.month", "Month");
        p.put("text.today", "Today");    
        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
        datePicker = new JDatePickerImpl(datePanel,new DateLabelFormatter());
        this.dtpFechaNaci = datePicker;
        pnlFecha.add(dtpFechaNaci);
        this.setSize(511, 430);
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitluo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        pnlRegistro = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        pnlGenero = new javax.swing.JPanel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        lblFechaNaci = new javax.swing.JLabel();
        pnlFecha = new javax.swing.JPanel();
        lblEmpresa = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtNomUsuario = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        psConstraseina = new javax.swing.JPasswordField();
        lblUbicacion = new javax.swing.JLabel();
        cbxUbicacion = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        lblTitluo.setText("REGISTRO DE VIGILANTE");
        pnlTitulo.add(lblTitluo);

        add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnRegistrar);

        add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pnlRegistro.setLayout(new java.awt.GridLayout(9, 2, 10, 10));

        lblCedula.setText("Digite la cedula");
        pnlRegistro.add(lblCedula);
        pnlRegistro.add(txtCedula);

        lblNombres.setText("Digite los nombres");
        pnlRegistro.add(lblNombres);
        pnlRegistro.add(txtNombres);

        lblApellidos.setText("Digite los apellidos");
        pnlRegistro.add(lblApellidos);
        pnlRegistro.add(txtApellidos);

        lblGenero.setText("Seleccione el genero");
        pnlRegistro.add(lblGenero);

        rbMasculino.setSelected(true);
        rbMasculino.setText("Masculino");
        pnlGenero.add(rbMasculino);

        rbFemenino.setText("Femenino");
        pnlGenero.add(rbFemenino);

        pnlRegistro.add(pnlGenero);

        lblFechaNaci.setText("Ingrese la fecha de nacimiento");
        pnlRegistro.add(lblFechaNaci);

        javax.swing.GroupLayout pnlFechaLayout = new javax.swing.GroupLayout(pnlFecha);
        pnlFecha.setLayout(pnlFechaLayout);
        pnlFechaLayout.setHorizontalGroup(
            pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );
        pnlFechaLayout.setVerticalGroup(
            pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        pnlRegistro.add(pnlFecha);

        lblEmpresa.setText("Digite la empresa a la cual pertenece");
        pnlRegistro.add(lblEmpresa);
        pnlRegistro.add(txtEmpresa);

        lblUsuario.setText("Digite un nombre de usuario");
        pnlRegistro.add(lblUsuario);
        pnlRegistro.add(txtNomUsuario);

        lblContrasenia.setText("Digita una contraseña");
        pnlRegistro.add(lblContrasenia);
        pnlRegistro.add(psConstraseina);

        lblUbicacion.setText("Seleccione su ubicacion");
        pnlRegistro.add(lblUbicacion);

        cbxUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salida_Norte", "Entrada_Sur" }));
        pnlRegistro.add(cbxUbicacion);

        add(pnlRegistro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(!camposValidos()){
            
        }else{
            Utilidades.mensajeError("Faltan campos por completar", "Campos Vacios");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
    private boolean camposValidos(){
        boolean completos = false;
        int a = txtApellidos.getText().length();
        int n = txtNombres.getText().length();
        int c = txtCedula.getText().length();
        int e = txtEmpresa.getText().length();
        int u = txtNomUsuario.getText().length();
        String password = "";
        for (int i = 0; i < psConstraseina.getPassword().length; i++) {
            password = password+psConstraseina.getPassword()[i];
        }
        int p = password.length();
        if(a>0 && n>0 && c>0 && e>0 && u>0 && p>0){
            completos = true;
        }
        return completos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxUbicacion;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblFechaNaci;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTitluo;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlFecha;
    private javax.swing.JPanel pnlGenero;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPasswordField psConstraseina;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNomUsuario;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
