/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicauca.parqueadero.presentacion;

import com.unicauca.parqueadero.negocio.GestorConductor;
import com.unicauca.parqueadero.utilidades.Utilidades;
import java.util.Observer;
import java.util.Properties;
import javafx.beans.InvalidationListener;
import javafx.beans.Observable;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import recursos.DateLabelFormatter;
/**
 *
 * @author JuanCamilo
 */
public class GUIRegistroConductor extends javax.swing.JFrame implements Observable{

    private JDatePickerImpl dtpFechaNaci;
    private  JDatePickerImpl datePicker;
    private GUIRegistroVehiculo vistaRVehiculo;
    /**
     * Creates new form GUIRegistroConductor
     */
    public GUIRegistroConductor() {
        initComponents();
        
    }
    public void iniciar(){
        UtilDateModel model = new UtilDateModel();
        Properties p = new Properties();
        p.put("text.year", "Year");
        p.put("text.month", "Month");
        p.put("text.today", "Today");    
        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
        datePicker = new JDatePickerImpl(datePanel,new DateLabelFormatter());
        this.dtpFechaNaci = datePicker;
        pnlFecha.add(dtpFechaNaci);
        this.setSize(500, 400);
        this.setVisible(true);
    }
    public void setRegistroVe(GUIRegistroVehiculo vista){
        this.vistaRVehiculo = vista;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        pnlResistro = new javax.swing.JPanel();
        pnlVehiculo = new javax.swing.JPanel();
        btnRegistrarCond = new javax.swing.JButton();
        btnRegistrarVehiculo = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        pblGeneros = new javax.swing.JPanel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        lblFecha = new javax.swing.JLabel();
        pnlFecha = new javax.swing.JPanel();
        lblRol = new javax.swing.JLabel();
        cbxRol = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 102, 102));

        pnlBotones.setBackground(new java.awt.Color(0, 102, 102));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        pnlBotones.add(btnCancelar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        lblTitulo.setBackground(new java.awt.Color(0, 102, 102));
        lblTitulo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("REGISTRO DE CONDUCTOR");
        getContentPane().add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        pnlResistro.setLayout(new java.awt.BorderLayout());

        pnlVehiculo.setBackground(new java.awt.Color(0, 102, 102));
        pnlVehiculo.setLayout(new java.awt.GridBagLayout());

        btnRegistrarCond.setText("Guardar Conductor");
        btnRegistrarCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCondActionPerformed(evt);
            }
        });
        pnlVehiculo.add(btnRegistrarCond, new java.awt.GridBagConstraints());

        btnRegistrarVehiculo.setText("Registrar Vehiculo");
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });
        pnlVehiculo.add(btnRegistrarVehiculo, new java.awt.GridBagConstraints());

        pnlResistro.add(pnlVehiculo, java.awt.BorderLayout.SOUTH);

        pnlDatos.setBackground(new java.awt.Color(0, 102, 102));
        pnlDatos.setForeground(new java.awt.Color(0, 102, 102));
        pnlDatos.setLayout(new java.awt.GridLayout(6, 2, 5, 18));

        lblCedula.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblCedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCedula.setText("Ingrese la Cedula");
        pnlDatos.add(lblCedula);
        pnlDatos.add(txtCedula);

        lblNombres.setBackground(new java.awt.Color(0, 102, 102));
        lblNombres.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombres.setText("Ingrese los Nombres");
        pnlDatos.add(lblNombres);
        pnlDatos.add(txtNombres);

        lblApellidos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApellidos.setText("Ingrese los apellidos:");
        pnlDatos.add(lblApellidos);
        pnlDatos.add(txtApellidos);

        lblGenero.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGenero.setText("Ingrese el genero");
        pnlDatos.add(lblGenero);

        pblGeneros.setBackground(new java.awt.Color(0, 102, 102));

        rbMasculino.setBackground(new java.awt.Color(0, 102, 102));
        rbMasculino.setForeground(new java.awt.Color(255, 255, 255));
        rbMasculino.setSelected(true);
        rbMasculino.setText("Masculino");
        pblGeneros.add(rbMasculino);

        rbFemenino.setBackground(new java.awt.Color(0, 102, 102));
        rbFemenino.setForeground(new java.awt.Color(255, 255, 255));
        rbFemenino.setText("Femenino");
        pblGeneros.add(rbFemenino);

        pnlDatos.add(pblGeneros);

        lblFecha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Ingrese la fecha de nacimiento");
        pnlDatos.add(lblFecha);
        pnlDatos.add(pnlFecha);

        lblRol.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblRol.setForeground(new java.awt.Color(255, 255, 255));
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRol.setText("Ingrese el rol del conductor");
        pnlDatos.add(lblRol);

        cbxRol.setBackground(new java.awt.Color(0, 153, 153));
        cbxRol.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbxRol.setForeground(new java.awt.Color(255, 255, 255));
        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente", "Administrativo", "Trabajador", "Visitante" }));
        pnlDatos.add(cbxRol);

        pnlResistro.add(pnlDatos, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlResistro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCondActionPerformed
        //TODO validaciones de campos
        GestorConductor gestor = new GestorConductor();
        String cedula,nombres,apellidos,fechaNaci,genero;
        cedula = txtCedula.getText();
        nombres = txtNombres.getText();
        apellidos =txtApellidos.getText();
        if(rbFemenino.isSelected()){
            genero = "F";
        }else{
            genero = "M";
        }
        fechaNaci = datePicker.getJFormattedTextField().getText();
        try {
            gestor.agregarConductor(cedula, nombres, apellidos, genero, fechaNaci);
            gestor.asociarRol(cedula, String.valueOf(cbxRol.getSelectedIndex()+1));
            Utilidades.mensajeExito("Conductor registrado con exito ","Exito");
            txtCedula.setEditable(false);
            txtNombres.setEditable(false);
            txtApellidos.setEditable(false);
            cbxRol.setEditable(false);
        } catch (Exception e) {
            Utilidades.mensajeError("Un error inesperado ha ocurrido","Error");
        }
        System.out.println(this.cbxRol.getSelectedIndex());
        
        
    }//GEN-LAST:event_btnRegistrarCondActionPerformed

    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
        vistaRVehiculo.iniciar();
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String cedula,placa;
        placa= Utilidades.placa;
        cedula = txtCedula.getText();
        GestorConductor g = new GestorConductor();
        try {
            g.asociarVehiCond(cedula, placa);
            Utilidades.mensajeExito("Datos Guardados Correctamente", "Exito");
            limpiarCajasTexto();
            this.dispose();
        } catch (Exception e) {
            Utilidades.mensajeError("Un error inesperado ha ocurrido", "Error");
                    
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private void limpiarCajasTexto(){
        System.out.println("TODO limpiar cajas");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegistrarCond;
    private javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pblGeneros;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlFecha;
    private javax.swing.JPanel pnlResistro;
    private javax.swing.JPanel pnlVehiculo;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(InvalidationListener il) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void removeListener(InvalidationListener il) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
