/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicauca.parqueadero.presentacion;

import com.unicauca.parqueadero.negocio.Multa;
import com.unicauca.parqueadero.negocio.Vehiculo;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JuanCamilo
 */
public class GUITablaMultas extends javax.swing.JFrame {

    /**
     * Creates new form GUITablaMultas
     */
    JFrame foto;
    JLabel lbl;
    BufferedImage imagen;
    public GUITablaMultas() {
        initComponents();
        inicializarTabla();
        Image icon = Toolkit.getDefaultToolkit().getImage("./src/recursos/papel.png");
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMultas = new javax.swing.JTable();

        tblMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMultas);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblMultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMultasMouseClicked
        int seleccionar = tblMultas.rowAtPoint(evt.getPoint());
        String ruta = String.valueOf(tblMultas.getValueAt(seleccionar, 2));
        foto = new JFrame();
        lbl = new JLabel();
        try {
            foto.setSize(400, 400);
            imagen = ImageIO.read(new File(ruta));
            lbl.setIcon(new ImageIcon(imagen));
            foto.getContentPane().add(lbl,BorderLayout.CENTER);
            foto.pack();
            foto.setLocationRelativeTo(null);
            foto.setVisible(true);
        } catch (Exception e) {
            System.out.println("Error cargando la foto");
        }
        
    }//GEN-LAST:event_tblMultasMouseClicked

    public void iniciar(String titulo, ArrayList<Multa> multas) {
        this.setSize(900, 135);
        this.setTitle("MULTAS REGISTRADAS PARA EL VEHICULO DE PLACAS: " + titulo);
        this.setLocationRelativeTo(null);
        llenarTabla(multas);
        this.setVisible(true);
    }

    private void inicializarTabla() {
        tblMultas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Fecha", "Descripcion","Ruta"
                }
        ));
    }

    public void llenarTabla(ArrayList<Multa> multas) {
        this.inicializarTabla();
        DefaultTableModel model = (DefaultTableModel) tblMultas.getModel();

        Object rowData[] = new Object[3];
        for (Multa m : multas) {
            rowData[0] = m.getFecha();
            rowData[1] = m.getDescripcion();
            rowData[2] = m.getFoto();
            model.addRow(rowData);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMultas;
    // End of variables declaration//GEN-END:variables

}
